---
    - name: Install Nginx using dnf
      dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Nginx using apt
      apt: 
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

