---
    - name: Create .repo file for local NGINX HTTP share if it does not exist
      copy:
        content: |
          [{{ item.id }}]
          name={{ item.name }}
          baseurl=http://localhost{{ repo_path }}/{{ item.os }}/{{ item.version }}/{{ item.name }}/packages/
          enabled={{ item.enable }}
          gpgcheck=1
          gpgkey=file://{{ repo_path }}/gpgkeys/{{ item.key }}
        dest: "{{ repo_path }}/yum-files/{{ item.id }}-local.repo"
      loop: "{{ repos }}"

