---
    - name: Create .repo file for external mirror if it does not exist
      copy:
        content: |
          [{{ item.id }}]
          name={{ item.name }}-{{ item.base }}
          baseurl={{ item.baseurl }}
          enabled={{ item.enabled }}
          gpgcheck=1
          gpgkey=file://{{ repo_path }}/gpgkeys/{{ item.key }}
        dest: "{{ repo_path }}/yum-files/external/{{ item.name }}-{{ item.version }}-{{ item.base }}-external.repo"
      loop: "{{ repos }}"
