---
# tasks file for repofiles
 - name: import check repofile
   ansible.builtin.import_tasks: checkfile.yaml

 - name: import	create external repo
   ansible.builtin.import_tasks: create-external-repo.yaml

 - name: import	create local repo
   ansible.builtin.import_tasks: create-local-repo.yaml

 - name: import	reposync config repo
   ansible.builtin.import_tasks: create-reposync-cfg.yaml 

 - name: import	check repofile
   ansible.builtin.import_tasks: check-repo.yaml
