---
 - name: install yum utils
   dnf:
    name: yum-utils
    state: present
   when: ansible_os_family == "RedHat"

 - name: install createrepo
   dnf:
     name: createrepo_c
     state: present
   when: ansible_os_family == "RedHat"